# This playbook configures an Ubuntu server to act as a development environment for the Airmee SDKs
---
-   name: 'Do basic startup and configuration tasks'
    hosts: all
    become: true
    become_user: root
    connection: local
    vars:
        infrastructure_directory: '/vagrant/infrastructure'
        application_directory: '/vagrant'

    tasks:

    ##########################################################################################################
    ## ADMIN USERS
    ##########################################################################################################

      - name: 'Create a group for the admin users'
        group:
            name: 'biometrix'
            state: present

      - name: 'Create a user'
        user:
            name: 'biometrix'
            shell: '/bin/bash'
            groups: 'biometrix'
            uid: '{{user_uid}}'

      - name: 'Add user to sudoers file'
        lineinfile:
            dest: '/etc/sudoers'
            state: present
            line: 'biometrix ALL=(ALL:ALL) NOPASSWD:ALL'

      - name: 'Add scripts directories to path'
        lineinfile:
            dest: '/home/biometrix/.bashrc'
            state: present
            line: 'PATH=$PATH:{{item}}'
        with_items:
          - '/vagrant/infrastructure/scripts:/vagrant/preprocessing/scripts:/vagrant/users/scripts:/vagrant/hardware/scripts'

    ##########################################################################################################
    ## AWS & PYTHON
    ##########################################################################################################

      - name: 'Add apt repository for python 3.6'
        apt_repository:
            repo: 'ppa:deadsnakes/ppa'
            state: present

      - name: 'Install AWS CLI and related tools'
        apt:
            name: '{{item}}'
            state: latest
        with_items:
          - 'jq'
          - 'python-pip'
          - 'python3.6'
          - 'python3-pip'
          - 'ntpdate'
          - 'nano'

      - name: 'Make python 3.6 the default'
        file:
            src: '{{ item.src }}'
            dest: '{{ item.dest }}'
            state: link
            force: true
        with_items:
            - { src: 'python3.6', dest: '/usr/bin/python3' }

      - name: 'Install pip tools (python 2)'
        pip:
            name: '{{item}}'
            state: latest
        with_items:
          - 'aws-mfa'
          - 'awscli'
          - 'boto3'
          - 'colorama'

      - name: 'Install pip tools (python 3)'
        pip:
            name: '{{item}}'
            state: latest
            executable: 'pip3'
        with_items:
          - 'boto3'
          - 'pandas' # Needed for get_cost_breakdown.py
          - 'colorama'

      - name: 'Create AWS config directory'
        file:
            path: '/root/.aws'
            state: directory
            owner: root
            group: root
            mode: 0700

      - name: 'Install AWS config files'
        copy:
            src: '{{infrastructure_directory}}/vagrant/ansible/files/aws/{{item}}'
            dest: '/root/.aws/{{item}}'
            owner: 'root'
            group: 'root'
            mode: '0600'
            force: No
        with_items:
          - "config"
          - "credentials"

      - name: 'Install supython'
        copy:
            src: '{{infrastructure_directory}}/vagrant/ansible/files/supython3'
            dest: '/usr/bin/supython3'
            owner: 'root'
            group: 'root'
            mode: '0755'

    ##########################################################################################################
    ## GIT
    ##########################################################################################################

      - name: 'Install Git'
        apt:
            name: '{{item}}'
            state: latest
        with_items:
          - 'git'

      - name: 'Allow SSH agent forwarding to be carried through `sudo`'
        lineinfile:
            path: '/etc/sudoers'
            line: 'Defaults env_keep+=SSH_AUTH_SOCK'
            insertafter: '^Defaults'

      - name: 'Set git config'
        git_config:
            name: '{{item.name}}'
            scope: system
            value: '{{item.value}}'
        with_items:
          - { name: 'user.name', value: '{{user_name}}' }
          - { name: 'user.email', value: '{{user_email}}' }