# This playbook configures an Ubuntu server to act as a development environment for the Airmee SDKs
---
-   name: 'Do basic startup and configuration tasks'
    hosts: all
    become: true
    become_user: root
    connection: local
    vars:
        infrastructure_directory: '/vagrant/Infrastructure'
        application_directory: '/vagrant'

    tasks:

    ##########################################################################################################
    ## BASIC CONFIGURATION
    ##########################################################################################################

      - name: "Set the server's hostname"
        hostname:
            name: 'biometrix'

    ##########################################################################################################
    ## ADMIN USERS
    ##########################################################################################################

      - name: 'Create a group for the admin users'
        group:
            name: '{{item | basename | splitext | first}}'
            state: present
        with_fileglob:
          - "{{infrastructure_directory}}/vagrant/ansible/authorized_keys/*.azk"

      - name: 'Create admin users'
        user:
            name: '{{item | basename | splitext | first}}'
            shell: '/bin/bash'
            groups: '{{item | basename | splitext | first}}'
            append: yes
        with_fileglob:
          - "{{infrastructure_directory}}/vagrant/ansible/authorized_keys/*.azk"

      - name: 'Add admin users to sudoers file'
        lineinfile:
            dest: '/etc/sudoers'
            state: present
            line: '{{item | basename | splitext | first}} ALL=(ALL:ALL) NOPASSWD:ALL'
        with_fileglob:
          - "{{infrastructure_directory}}/vagrant/ansible/authorized_keys/*.azk"

      - name: 'Create .ssh directory for admin users'
        file:
            path: '/home/{{item | basename | splitext | first}}/.ssh'
            state: directory
            owner: '{{item | basename | splitext | first}}'
            group: '{{item | basename | splitext | first}}'
            mode: 0700
        with_fileglob:
          - "{{infrastructure_directory}}/vagrant/ansible/authorized_keys/*.azk"

      - name: 'Install SSH public key'
        copy:
            src: '{{item}}'
            dest: '/home/{{item | basename | splitext | first}}/.ssh/authorized_keys'
            owner: '{{item | basename | splitext | first}}'
            group: '{{item | basename | splitext | first}}'
            mode: '0700'
        with_fileglob:
          - "{{infrastructure_directory}}/vagrant/ansible/authorized_keys/*.azk"

    ##########################################################################################################
    ## AWS & PYTHON
    ##########################################################################################################

      - name: 'Install AWS CLI and related tools'
        apt:
            name: '{{item}}'
            state: latest
        with_items:
          - 'jq'
          - 'python-pip'
          - 'python3-pip'
          - 'ntpdate'

      - name: 'Install pip tools (python 2)'
        pip:
            name: '{{item}}'
            state: latest
        with_items:
          - 'aws-mfa'
          - 'awscli'
          - 'boto3'
          - 'colorama'

      - name: 'Install pip tools (python 3)'
        pip:
            name: '{{item}}'
            state: latest
            executable: 'pip3'
        with_items:
          - 'boto3'
          - 'pandas' # Needed for get_cost_breakdown.py
          - 'colorama'

      - name: 'Create AWS config directory'
        file:
            path: '/root/.aws'
            state: directory
            owner: root
            group: root
            mode: 0700

      - name: 'Install AWS config files'
        copy:
            src: '{{infrastructure_directory}}/vagrant/ansible/files/aws/{{item}}'
            dest: '/root/.aws/{{item}}'
            owner: 'root'
            group: 'root'
            mode: '0600'
            force: No
        with_items:
          - "config"
          - "credentials"

      - name: 'Install supython'
        copy:
            src: '{{infrastructure_directory}}/vagrant/ansible/files/supython3'
            dest: '/usr/bin/supython3'
            owner: 'root'
            group: 'root'
            mode: '0755'

    ##########################################################################################################
    ## GIT
    ##########################################################################################################

      - name: 'Install Docker'
        apt:
            name: '{{item}}'
            state: latest
        with_items:
          - 'git'

      - name: 'Allow SSH agent forwarding to be carried through `sudo`'
        lineinfile:
            path: '/etc/sudoers'
            line: 'Defaults env_keep+=SSH_AUTH_SOCK'
            insertafter: '^Defaults'

    ##########################################################################################################
    ## DOCKER
    ##########################################################################################################

      - name: 'Install Docker'
        apt:
            name: '{{item}}'
            state: latest
        with_items:
          - 'docker.io'

    ##########################################################################################################
    ## DOCKER-ECR CREDENTIAL HELPER
    ##########################################################################################################

      - name: "Clone the git repository"
        git:
            depth: 1
            dest: "/tmp/amazon-ecr-credential-helper"
            repo: "https://github.com/awslabs/amazon-ecr-credential-helper.git"

      - name: "Check if the binary has already been built"
        stat:
            path: "/tmp/amazon-ecr-credential-helper/bin/local/docker-credential-ecr-login"
        register: "docker_credential_ect_login"

      - name: "Ensure make is installed to build the binary"
        apt:
            name: "make"
            state: "installed"

      - name: "Build the binary inside a docker container"
        make:
            chdir: "/tmp/amazon-ecr-credential-helper"
            target: "docker"
        when: "docker_credential_ect_login.stat.exists == False"

      - name: "Move the binary into position"
        copy:
            remote_src: True
            dest: "/usr/bin/docker-credential-ecr-login"
            group: "root"
            mode: "0755"
            owner: "root"
            src: "/tmp/amazon-ecr-credential-helper/bin/local/docker-credential-ecr-login"

      - name: "Create root's .docker directory"
        file:
            dest: "/root/.docker"
            group: "root"
            owner: "root"
            state: "directory"

      - name: "Create root's docker config file"
        copy:
            content: '{"credsStore": "ecr-login"}'
            dest: "/root/.docker/config.json"
            group: "root"
            owner: "root"

    ##########################################################################################################
    ## PACKER
    ##########################################################################################################

      - name: "Ensure unzip is installed"
        apt:
            name: "unzip"
            state: "installed"

      - name: 'Install Packer'
        unarchive:
            dest: '/usr/local/bin'
            group: 'root'
            mode: '755'
            owner: 'root'
            remote_src: 'yes'
            src: 'https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_amd64.zip'

    ##########################################################################################################
    ## RUBY
    ##########################################################################################################

      - name: 'Latest version of Ruby is installed'
        apt:
            name: '{{ item }}'
            state: latest
        with_items:
          - 'ruby'
          - 'ruby-dev'
          - 'zlib1g-dev'
          - 'libpq-dev'
